# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchandSort.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UserInterface(object):
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow
        self.setup()

    def setup(self):
        self.setupUi(self.MainWindow)
        self.retranslateUi(self.MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 9, 721, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stepButton = QtWidgets.QPushButton(self.frame)
        self.stepButton.setGeometry(QtCore.QRect(10, 440, 151, 60))
        self.stepButton.setObjectName("stepButton")
        # self.backwardButton = QtWidgets.QPushButton(self.frame)
        # self.backwardButton.setGeometry(QtCore.QRect(86, 500, 75, 60))
        # self.backwardButton.setObjectName("backwardButton")
        self.finishButton = QtWidgets.QPushButton(self.frame)
        self.finishButton.setGeometry(QtCore.QRect(10, 500, 151, 60))
        self.finishButton.setObjectName("finishButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 10, 81, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 10, 161, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.numQtyComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.numQtyComboBox.setObjectName("numQtyComboBox")
        self.verticalLayout_6.addWidget(self.numQtyComboBox)
        self.algoComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.algoComboBox.setObjectName("algoComboBox")
        self.verticalLayout_6.addWidget(self.algoComboBox)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(500, 70, 160, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.alertMessage = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.alertMessage.setObjectName("alertMessage")
        self.verticalLayout_8.addWidget(self.alertMessage)
        self.initButton = QtWidgets.QPushButton(self.frame)
        self.initButton.setGeometry(QtCore.QRect(10, 10, 151, 121))
        self.initButton.setObjectName("initButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 70, 81, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.alertLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.alertLabel.setObjectName("alertLabel")
        self.verticalLayout_7.addWidget(self.alertLabel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionToggleButton = QtWidgets.QPushButton(self.frame)
        self.actionToggleButton.setGeometry(QtCore.QRect(290, 10, 121, 61))
        self.actionToggleButton.setObjectName("actionToggleButton")
        self.actionLabel = QtWidgets.QLabel(self.frame)
        self.actionLabel.setGeometry(QtCore.QRect(180, 9, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionLabel.setFont(font)
        self.actionLabel.setObjectName("actionLabel")
        self.actionTypeLabel = QtWidgets.QLabel(self.frame)
        self.actionTypeLabel.setGeometry(QtCore.QRect(170, 80, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        font.setUnderline(True)
        self.actionTypeLabel.setFont(font)
        self.actionTypeLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.actionTypeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.actionTypeLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.actionTypeLabel.setScaledContents(True)
        self.actionTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionTypeLabel.setWordWrap(False)
        self.actionTypeLabel.setObjectName("actionTypeLabel")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(170, 440, 91, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(260, 440, 160, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.searchInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.searchInput.setObjectName("searchInput")
        self.verticalLayout_10.addWidget(self.searchInput)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(170, 500, 91, 61))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(260, 500, 160, 61))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.runtimeNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.runtimeNumber.setObjectName("runtimeNumber")
        self.verticalLayout_12.addWidget(self.runtimeNumber)
        self.displayTable = QtWidgets.QTableWidget(self.frame)
        self.displayTable.setGeometry(QtCore.QRect(440, 450, 261, 111))
        self.displayTable.setObjectName("displayTable")
        self.displayTable.setColumnCount(2)
        # self.displayTable.setRowCount(self.tableRowCount)
        self.displayTable.setHorizontalHeaderLabels(["Algorithm", "Action"])
        self.displayFrame = QtWidgets.QFrame(self.frame)
        self.displayFrame.setGeometry(QtCore.QRect(10, 140, 681, 291))
        self.displayFrame.setAutoFillBackground(False)
        self.displayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.displayFrame.setLineWidth(0)
        self.displayFrame.setObjectName("displayFrame")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.displayFrame)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 681, 291))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.displayLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.displayLayout.setContentsMargins(0, 0, 0, 0)
        self.displayLayout.setObjectName("displayLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Search & Sort Algorithums"))
        self.stepButton.setText(_translate("MainWindow", "Step"))
        # self.backwardButton.setText(_translate("MainWindow", "Backward"))
        self.finishButton.setText(_translate("MainWindow", "Finish"))
        self.label.setText(_translate("MainWindow", "Numbers:"))
        self.label_2.setText(_translate("MainWindow", "Algorithm:"))
        self.alertLabel.setText(_translate("MainWindow", ""))
        self.alertMessage.setText(_translate("MainWindow", ""))
        self.initButton.setText(_translate("MainWindow", "Initialize"))
        self.actionToggleButton.setText(_translate("MainWindow", "Toggle"))
        self.actionToggleButton.setCheckable(True)
        self.actionLabel.setText(_translate("MainWindow", "Action Type:"))
        self.actionTypeLabel.setText(_translate("MainWindow", "Sort"))
        self.label_7.setText(_translate("MainWindow", "Search For:"))
        self.label_8.setText(_translate("MainWindow", "Runtime:"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new file"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))